general:
  kafka-topic: transactions
spring:
  kafka:
    consumer:
      group-id: midas-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'com.jpmc.midascore.foundation'
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer